# 01. Import libraries

In [2]:
import pandas as pd
import numpy as np
import os

# 02. Import data

In [5]:
# Import pkl data 
path = '/Users/bobbi/Careerfoundry/InstacartBasketAnalysis_01_25'

df_ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared data', 'merged_ords_prods.pkl'))

df_ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,existing_merge,product_name,aisle_id,department_id,prices,_merge
0,2539329,1,1,2,8,NaN,196,1,0,both,Soda,77,7,9.0,both
1,2539329,1,1,2,8,NaN,14084,2,0,both,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both
2,2539329,1,1,2,8,NaN,12427,3,0,both,Original Beef Jerky,23,19,4.4,both
3,2539329,1,1,2,8,NaN,26088,4,0,both,Aged White Cheddar Popcorn,23,19,4.7,both
4,2539329,1,1,2,8,NaN,26405,5,0,both,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both


In [7]:
df = df_ords_prods_merge[:1000000]

In [9]:
df.shape

(1000000, 15)

# 03. Functions

### If-Statements with User-Defined Functions

In [12]:
# define a price label function

def price_label(row):
  if row['prices'] <= 5:
    return 'Low-range product'
  elif (row['prices'] > 5) and (row['prices'] <= 15):
    return 'Mid-range product'
  elif row['prices'] > 15:
    return 'High range'
  else: return 'Not enough data'

In [14]:
# Create a price_range column
df['price_range'] = df.apply(price_label, axis = 1)

df.head()

/var/folders/bs/25x482152nx68y1wp8l2g42c0000gn/T/ipykernel_36021/158387950.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price_range'] = df.apply(price_label, axis = 1)


,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,existing_merge,product_name,aisle_id,department_id,prices,_merge,price_range
0,2539329,1,1,2,8,NaN,196,1,0,both,Soda,77,7,9.0,both,Mid-range product
1,2539329,1,1,2,8,NaN,14084,2,0,both,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Mid-range product
2,2539329,1,1,2,8,NaN,12427,3,0,both,Original Beef Jerky,23,19,4.4,both,Low-range product
3,2539329,1,1,2,8,NaN,26088,4,0,both,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product
4,2539329,1,1,2,8,NaN,26405,5,0,both,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Low-range product


In [15]:
df['price_range'].value_counts()

price_range
Mid-range product    673183
Low-range product    314392
High range            12425
Name: count, dtype: int64

In [16]:
df['prices'].max()

99999.0

In [20]:
df_ords_prods_merge['prices'].max()

99999.0

In [22]:
print(df['price_range'] == 'High range')

0         False
1         False
2         False
3         False
4         False
          ...  
999995    False
999996    False
999997    False
999998    False
999999    False
Name: price_range, Length: 1000000, dtype: bool


In [24]:
print(df.loc[df['price_range'] == 'High range', 'prices'])

398       19.6
401       19.6
436       23.2
465       23.2
480       23.2
          ... 
999329    24.6
999332    25.0
999388    25.0
999394    19.6
999880    20.8
Name: prices, Length: 12425, dtype: float64


### If-Statements with the loc() Function

In [26]:
# If statement with loc() function
df.loc[df['prices'] > 15, 'price_range_loc'] = 'High-range product'

/var/folders/bs/25x482152nx68y1wp8l2g42c0000gn/T/ipykernel_36021/3509703962.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['prices'] > 15, 'price_range_loc'] = 'High-range product'


In [28]:
df.loc[(df['prices'] <= 15) & (df['prices'] > 5), 'price_range_loc'] = 'Mid-range product'

In [30]:
df.loc[df['prices'] <= 5, 'price_range_loc'] = 'Low-range product'

In [32]:
df['price_range_loc'].value_counts(dropna = False)

price_range_loc
Mid-range product     673183
Low-range product     314392
High-range product     12425
Name: count, dtype: int64

#### In this following section I tried to make sense of the outliners in price. I found two at 99999.0 and 14900.0 that didn't make sense

In [34]:
df.describe()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,aisle_id,department_id,prices
count,1.000000e+06,1000000.000000,1000000.000000,1000000.000000,1000000.000000,936384.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,1.712098e+06,3295.070459,17.313612,2.765702,13.416690,11.062006,25595.891283,8.312942,0.590985,71.058417,9.984846,11.396794
std,9.870102e+05,1866.882221,17.931306,2.091348,4.221497,8.811708,14077.246950,7.208310,0.491652,38.228388,6.294836,425.994349
min,8.000000e+00,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000
25%,8.620670e+05,1699.000000,5.000000,1.000000,10.000000,5.000000,13536.000000,3.000000,0.000000,31.000000,4.000000,4.200000
50%,1.711365e+06,3350.000000,11.000000,3.000000,13.000000,8.000000,25340.000000,6.000000,1.000000,83.000000,9.000000,7.400000
75%,2.563843e+06,4937.000000,24.000000,5.000000,16.000000,15.000000,37825.000000,11.000000,1.000000,107.000000,16.000000,11.300000
max,3.420853e+06,6474.000000,99.000000,6.000000,23.000000,30.000000,49687.000000,95.000000,1.000000,134.000000,21.000000,99999.000000


In [36]:
df[df['prices'] == 99999.0]

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,existing_merge,product_name,aisle_id,department_id,prices,_merge,price_range,price_range_loc
128911,183964,873,3,0,10,7.0,33664,11,0,both,2 % Reduced Fat Milk,84,16,99999.0,both,High range,High-range product
128924,1851256,873,4,6,12,13.0,33664,8,1,both,2 % Reduced Fat Milk,84,16,99999.0,both,High range,High-range product
284218,1915696,1893,1,5,17,NaN,33664,10,0,both,2 % Reduced Fat Milk,84,16,99999.0,both,High range,High-range product
284229,2763293,1893,2,4,16,13.0,33664,6,1,both,2 % Reduced Fat Milk,84,16,99999.0,both,High range,High-range product
284252,2564805,1893,4,1,17,30.0,33664,3,1,both,2 % Reduced Fat Milk,84,16,99999.0,both,High range,High-range product
499076,949012,3339,1,1,14,NaN,33664,8,0,both,2 % Reduced Fat Milk,84,16,99999.0,both,High range,High-range product
499119,420057,3339,2,0,11,13.0,33664,29,1,both,2 % Reduced Fat Milk,84,16,99999.0,both,High range,High-range product
499141,1511997,3339,3,1,18,8.0,33664,14,1,both,2 % Reduced Fat Milk,84,16,99999.0,both,High range,High-range product
499158,1153448,3339,4,4,16,10.0,33664,1,1,both,2 % Reduced Fat Milk,84,16,99999.0,both,High range,High-range product
499180,2669259,3339,5,4,14,21.0,33664,6,1,both,2 % Reduced Fat Milk,84,16,99999.0,both,High range,High-range product


In [38]:
df_ords_prods_merge[df_ords_prods_merge['prices'] == 99999.0]

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,existing_merge,product_name,aisle_id,department_id,prices,_merge
128911,183964,873,3,0,10,7.0,33664,11,0,both,2 % Reduced Fat Milk,84,16,99999.0,both
128924,1851256,873,4,6,12,13.0,33664,8,1,both,2 % Reduced Fat Milk,84,16,99999.0,both
284218,1915696,1893,1,5,17,NaN,33664,10,0,both,2 % Reduced Fat Milk,84,16,99999.0,both
284229,2763293,1893,2,4,16,13.0,33664,6,1,both,2 % Reduced Fat Milk,84,16,99999.0,both
284252,2564805,1893,4,1,17,30.0,33664,3,1,both,2 % Reduced Fat Milk,84,16,99999.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32079919,2249946,204099,29,0,8,4.0,33664,1,0,both,2 % Reduced Fat Milk,84,16,99999.0,both
32079936,2363282,204099,31,0,9,2.0,33664,1,1,both,2 % Reduced Fat Milk,84,16,99999.0,both
32125745,3181945,204395,13,3,15,8.0,33664,25,0,both,2 % Reduced Fat Milk,84,16,99999.0,both
32255078,2486215,205227,7,3,20,4.0,33664,8,0,both,2 % Reduced Fat Milk,84,16,99999.0,both


In [40]:
df_ords_prods_merge[df_ords_prods_merge['prices'] == 14900.0]

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,existing_merge,product_name,aisle_id,department_id,prices,_merge
1576,912404,17,12,2,14,5.0,21553,5,0,both,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both
1638,603376,17,22,6,16,4.0,21553,3,1,both,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both
16522,3264360,135,2,2,21,13.0,21553,6,0,both,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both
16528,892534,135,3,0,8,12.0,21553,3,1,both,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both
53672,229704,342,8,1,19,30.0,21553,9,0,both,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32320511,3172853,205650,18,1,9,7.0,21553,17,1,both,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both
32347717,2504315,205818,3,5,15,3.0,21553,13,0,both,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both
32347727,1108388,205818,5,4,5,1.0,21553,5,1,both,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both
32380527,1916142,206049,1,2,17,NaN,21553,2,0,both,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both


In [42]:
df_ords_prods_merge[df_ords_prods_merge['product_id'] == 21553]

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,existing_merge,product_name,aisle_id,department_id,prices,_merge
1576,912404,17,12,2,14,5.0,21553,5,0,both,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both
1638,603376,17,22,6,16,4.0,21553,3,1,both,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both
16522,3264360,135,2,2,21,13.0,21553,6,0,both,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both
16528,892534,135,3,0,8,12.0,21553,3,1,both,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both
53672,229704,342,8,1,19,30.0,21553,9,0,both,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32320511,3172853,205650,18,1,9,7.0,21553,17,1,both,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both
32347717,2504315,205818,3,5,15,3.0,21553,13,0,both,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both
32347727,1108388,205818,5,4,5,1.0,21553,5,1,both,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both
32380527,1916142,206049,1,2,17,NaN,21553,2,0,both,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both


In [44]:
df_ords_prods_merge.shape

(32404859, 15)

In [46]:
df_ords_prods_merge.loc[df_ords_prods_merge['product_name'] == '2% Reduced Fat Milk']

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,existing_merge,product_name,aisle_id,department_id,prices,_merge
4754,1244041,38,5,0,14,22.0,23909,14,0,both,2% Reduced Fat Milk,84,16,9.2,both
4766,718156,38,6,6,9,13.0,23909,7,1,both,2% Reduced Fat Milk,84,16,9.2,both
4784,894015,38,7,6,10,28.0,23909,8,1,both,2% Reduced Fat Milk,84,16,9.2,both
5274,2315446,42,11,3,18,19.0,23909,2,0,both,2% Reduced Fat Milk,84,16,9.2,both
5319,606677,43,1,1,18,NaN,23909,4,0,both,2% Reduced Fat Milk,84,16,9.2,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32403069,2547959,206201,28,0,13,1.0,23909,1,1,both,2% Reduced Fat Milk,84,16,9.2,both
32403076,1046357,206201,29,4,21,4.0,23909,1,1,both,2% Reduced Fat Milk,84,16,9.2,both
32403085,584166,206201,30,0,7,24.0,23909,3,1,both,2% Reduced Fat Milk,84,16,9.2,both
32403111,1125912,206201,31,1,11,22.0,23909,4,1,both,2% Reduced Fat Milk,84,16,9.2,both


In [48]:
# Replace 99999.0 price for 9.2 price 
df_ords_prods_merge['prices'].replace(99999.0, 9.2, inplace=True)

/var/folders/bs/25x482152nx68y1wp8l2g42c0000gn/T/ipykernel_36021/1643870883.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ords_prods_merge['prices'].replace(99999.0, 9.2, inplace=True)


In [50]:
df_ords_prods_merge[df_ords_prods_merge['product_id'] == 33664]

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,existing_merge,product_name,aisle_id,department_id,prices,_merge
128911,183964,873,3,0,10,7.0,33664,11,0,both,2 % Reduced Fat Milk,84,16,9.2,both
128924,1851256,873,4,6,12,13.0,33664,8,1,both,2 % Reduced Fat Milk,84,16,9.2,both
284218,1915696,1893,1,5,17,NaN,33664,10,0,both,2 % Reduced Fat Milk,84,16,9.2,both
284229,2763293,1893,2,4,16,13.0,33664,6,1,both,2 % Reduced Fat Milk,84,16,9.2,both
284252,2564805,1893,4,1,17,30.0,33664,3,1,both,2 % Reduced Fat Milk,84,16,9.2,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32079919,2249946,204099,29,0,8,4.0,33664,1,0,both,2 % Reduced Fat Milk,84,16,9.2,both
32079936,2363282,204099,31,0,9,2.0,33664,1,1,both,2 % Reduced Fat Milk,84,16,9.2,both
32125745,3181945,204395,13,3,15,8.0,33664,25,0,both,2 % Reduced Fat Milk,84,16,9.2,both
32255078,2486215,205227,7,3,20,4.0,33664,8,0,both,2 % Reduced Fat Milk,84,16,9.2,both


In [58]:
df_ords_prods_merge.loc[df_ords_prods_merge['aisle_id'] == 108, 'product_name'].unique()

array(['Part Skim Ricotta Cheese', 'Whipped Cream Cheese',
       'Lowfat Small Curd Cottage Cheese',
       'Organic Cultured Cream Cheese Spread',
       'Lowfat 2% Milkfat Cottage Cheese',
       'Original Whipped Cream Cheese', 'Sour Cream',
       'Original Cream Cheese', 'Pure & Natural Sour Cream',
       'Philadelphia Original Cream Cheese', 'Whole Milk Ricotta Cheese',
       'Original Sour Cream', 'Cream Cheese Bar', 'Light Sour Cream',
       'Creme Fraiche', 'Organic Small Curd Cottage Cheese',
       'Organic Sour Cream',
       'Small Curd Lowfat 2% Milkfat Cottage Cheese',
       'Organic Cream Cheese Bar', 'Pimento Cheese Dip',
       'Organic Strawberry Chia Lowfat 2% Cottage Cheese',
       'Organic Cottage Cheese Blueberry Acai Chia',
       'Cream Cheese Spread',
       'Dairy Free Plain Cream Cheese Style Spread',
       'Philadelphia Cream Cheese', 'Cream Cheese',
       'Dairy-Free Chive Cream Cheese', 'Natural Sour Cream',
       'The Natural Whipped Topping', '

In [60]:
df_ords_prods_merge.loc[df_ords_prods_merge['product_name'] == '2% Low-fat Cottage Cheese']

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,existing_merge,product_name,aisle_id,department_id,prices,_merge
38796,589249,262,27,5,15,6.0,11259,8,0,both,2% Low-fat Cottage Cheese,108,16,9.4,both
180766,1011761,1221,1,5,13,NaN,11259,14,0,both,2% Low-fat Cottage Cheese,108,16,9.4,both
180786,777715,1221,2,6,16,8.0,11259,13,1,both,2% Low-fat Cottage Cheese,108,16,9.4,both
180810,2276348,1221,3,2,8,10.0,11259,12,1,both,2% Low-fat Cottage Cheese,108,16,9.4,both
180825,772394,1221,4,0,12,5.0,11259,9,1,both,2% Low-fat Cottage Cheese,108,16,9.4,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31918826,798137,203062,2,0,18,30.0,11259,2,1,both,2% Low-fat Cottage Cheese,108,16,9.4,both
31918858,2890120,203062,6,1,21,30.0,11259,4,1,both,2% Low-fat Cottage Cheese,108,16,9.4,both
31960268,3135231,203313,13,4,7,16.0,11259,16,0,both,2% Low-fat Cottage Cheese,108,16,9.4,both
31999082,3115325,203530,5,3,10,2.0,11259,9,0,both,2% Low-fat Cottage Cheese,108,16,9.4,both


In [62]:
# Replace Lowfat 2% Milkfat Cottage Cheese from 14900.0	to 2% Low-fat Cottage Cheese = 9.4	
df_ords_prods_merge['prices'].replace(14900.0, 9.4, inplace=True)

/var/folders/bs/25x482152nx68y1wp8l2g42c0000gn/T/ipykernel_36021/151309337.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ords_prods_merge['prices'].replace(14900.0, 9.4, inplace=True)


In [64]:
df_ords_prods_merge[df_ords_prods_merge['product_id'] == 21553]

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,existing_merge,product_name,aisle_id,department_id,prices,_merge
1576,912404,17,12,2,14,5.0,21553,5,0,both,Lowfat 2% Milkfat Cottage Cheese,108,16,9.4,both
1638,603376,17,22,6,16,4.0,21553,3,1,both,Lowfat 2% Milkfat Cottage Cheese,108,16,9.4,both
16522,3264360,135,2,2,21,13.0,21553,6,0,both,Lowfat 2% Milkfat Cottage Cheese,108,16,9.4,both
16528,892534,135,3,0,8,12.0,21553,3,1,both,Lowfat 2% Milkfat Cottage Cheese,108,16,9.4,both
53672,229704,342,8,1,19,30.0,21553,9,0,both,Lowfat 2% Milkfat Cottage Cheese,108,16,9.4,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32320511,3172853,205650,18,1,9,7.0,21553,17,1,both,Lowfat 2% Milkfat Cottage Cheese,108,16,9.4,both
32347717,2504315,205818,3,5,15,3.0,21553,13,0,both,Lowfat 2% Milkfat Cottage Cheese,108,16,9.4,both
32347727,1108388,205818,5,4,5,1.0,21553,5,1,both,Lowfat 2% Milkfat Cottage Cheese,108,16,9.4,both
32380527,1916142,206049,1,2,17,NaN,21553,2,0,both,Lowfat 2% Milkfat Cottage Cheese,108,16,9.4,both


There were two outliners that didn't make sense '2% Reduced Fat Milk' at 99999.0 price and 2% Low-fat Cottage Cheese at 14900.0. I looked in the data for a similar product to find the price and then replace the wrong price to the corresponding price.

In [67]:
df = df_ords_prods_merge[:1000000]

In [75]:
df['price_range'] = df.apply(price_label, axis = 1)

df['price_range'].value_counts()

/var/folders/bs/25x482152nx68y1wp8l2g42c0000gn/T/ipykernel_36021/1238421286.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price_range'] = df.apply(price_label, axis = 1)


price_range
Mid-range product    673340
Low-range product    314392
High range            12268
Name: count, dtype: int64

In [77]:
df['prices'].max()

25.0

### If-Statements with For-Loops

In [81]:
df_ords_prods_merge['orders_day_of_week'].value_counts(dropna = False)

orders_day_of_week
0    6204182
1    5660230
6    4496490
2    4213830
5    4205791
3    3840534
4    3783802
Name: count, dtype: int64

In [85]:
# Create new column busiest day

result = []

for value in df_ords_prods_merge["orders_day_of_week"]:
    if value == 0:
        result.append("Busiest day")
    elif value == 4:
        result.append("Least busy")
    else:
        result.append("Regularly busy")

In [87]:
result

['Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy

In [89]:
df_ords_prods_merge['busiest_day'] = result

In [91]:
df_ords_prods_merge['busiest_day'].value_counts(dropna = False)

busiest_day
Regularly busy    22416875
Busiest day        6204182
Least busy         3783802
Name: count, dtype: int64

Create a new column busiest_days

In [104]:
# Create a new array for new results
new_results = []

for value in df_ords_prods_merge['orders_day_of_week']:
    if value == 0 or value == 1:
        new_results.append("Busiest days")
    elif value == 4 or value == 3:
        new_results.append("Least busy days")
    else:
        new_results.append("Regularly busy")

In [106]:
# Use new array in the existing 'busiest_day' column
df_ords_prods_merge['busiest_day'] = new_results

In [101]:
df_ords_prods_merge['busiest_day'].value_counts(dropna = False)

busiest_day
Regularly busy     12916111
Busiest days       11864412
Least busy days     7624336
Name: count, dtype: int64

In [108]:
# Rename column
df_ords_prods_merge.rename(columns={'busiest_day': 'busiest_days'}, inplace=True)

In [110]:
df_ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,existing_merge,product_name,aisle_id,department_id,prices,_merge,busiest_days
0,2539329,1,1,2,8,NaN,196,1,0,both,Soda,77,7,9.0,both,Regularly busy
1,2539329,1,1,2,8,NaN,14084,2,0,both,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Regularly busy
2,2539329,1,1,2,8,NaN,12427,3,0,both,Original Beef Jerky,23,19,4.4,both,Regularly busy
3,2539329,1,1,2,8,NaN,26088,4,0,both,Aged White Cheddar Popcorn,23,19,4.7,both,Regularly busy
4,2539329,1,1,2,8,NaN,26405,5,0,both,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Regularly busy


### Identify busies hours of the day 

In [121]:
# Identify order frequency per hour

hourly_counts = df_ords_prods_merge['order_hour_of_day'].value_counts(dropna = False)

hourly_counts

order_hour_of_day
10    2761760
11    2736140
14    2689136
15    2662144
13    2660954
12    2618532
16    2535202
9     2454203
17    2087654
8     1718118
18    1636502
19    1258305
20     976156
7      891054
21     795637
22     634225
23     402316
6      290493
0      218769
1      115700
5       87961
2       69375
4       53242
3       51281
Name: count, dtype: int64

As the technical officer wants to separate orders per hour in three periods, I decided to establish this separation:   
* "Most orders": Above 2 million orders per hour
* "Average orders": Under 2 million orders and above 500.000 orders per hour
* "Fewest orders": Under 500.000 orders per hour

I will use the calculated hours to create a function to classify the periods and then apply it to create a new colum 'busiest_period_of_day'

In [123]:
# Function

def hour_classification(hour):
    count = hourly_counts[hour]
    if count >= 2000000:
        return "Most orders"
    elif count < 2000000 and count >= 500000:
        return "Average orders"
    else:
        return "Fewest orders"

In [127]:
# Apply classification 

df_ords_prods_merge['busiest_period_of_day'] = df_ords_prods_merge['order_hour_of_day'].apply(hour_classification)

In [129]:
df_ords_prods_merge['busiest_period_of_day'].value_counts(dropna = False)

busiest_period_of_day
Most orders       23205725
Average orders     7909997
Fewest orders      1289137
Name: count, dtype: int64

In [131]:
df_ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,existing_merge,product_name,aisle_id,department_id,prices,_merge,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,196,1,0,both,Soda,77,7,9.0,both,Regularly busy,Average orders
1,2539329,1,1,2,8,NaN,14084,2,0,both,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Regularly busy,Average orders
2,2539329,1,1,2,8,NaN,12427,3,0,both,Original Beef Jerky,23,19,4.4,both,Regularly busy,Average orders
3,2539329,1,1,2,8,NaN,26088,4,0,both,Aged White Cheddar Popcorn,23,19,4.7,both,Regularly busy,Average orders
4,2539329,1,1,2,8,NaN,26405,5,0,both,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Regularly busy,Average orders


# 04. Export data

In [134]:
df_ords_prods_merge.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_busy_day_hour_7.pkl'))